# Generated by Django 3.1.7 on 2021-04-08 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='timeslot',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
