# Generated by Django 3.1.7 on 2021-04-08 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20210408_1756'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='relax date')),
                ('plannedtime', models.CharField(choices=[('M', 'Morning'), ('A', 'Afternoon'), ('N', 'Night')], default='M', max_length=12)),
            ],
        ),
    ]
