# Generated by Django 3.1.7 on 2021-04-09 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_relax'),
    ]

    operations = [
        migrations.AddField(
            model_name='relax',
            name='checklist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.checklist'),
            preserve_default=False,
        ),
    ]
