# Generated by Django 3.1.7 on 2021-04-09 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20210409_2025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checklist',
            old_name='vacation',
            new_name='vacations',
        ),
    ]
